### ISSUE TITLE
Peer to Peer code review

### ISSUE THREAD

**Issue by quavo19** [iamchristianani/to-do-list#5]
Hi @iamchristianani, this is your morning session team.

You did a great job working on this milestone, your project is complete! 🚀 
There is nothing else to say other than... it's time to merge it 🤖  
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

## Highlights
✅ Great use of GitHub flow. 💯 
✅ Descriptive PR title, summary and commit messages. 💬 

Feel free to leave any questions or comments in the issues thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**Comment by iamchristianani** [comment]
Thank you ❤️
