### ISSUE TITLE
Peer to peer code review Module 2, week 3, day 2

### ISSUE THREAD

**Issue by EddyShimwa** [iamchristianani/to-do-list#6]
Your project is complete! You have done it exceptionally well. it's time to merge it 💯

Congratulations! 🎉

![leonardo-di-caprio-wolf-of-wall-street](https://user-images.githubusercontent.com/88631022/208606202-5bf1654b-8eae-4ffa-a042-a6c77eda1d15.gif)

To Highlight 👍
✔️ Good design
✔️ No linter errors.
✔️ Descriptive readme file.
✔️The live demo link is there
✔️ Well-implemented requirements.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by iamchristianani** [comment]
Thank you for the review 🙇
